// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRCockpit.Infrastructure.Persistence;

#nullable disable

namespace PRCockpit.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PrCockpitContext))]
    [Migration("20260920090158_AddExplanationBlobId")]
    partial class AddExplanationBlobId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRCockpit.Infrastructure.Persistence.Entities.PrChecklistRow", b =>
                {
                    b.Property<string>("Organization")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Project")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RepositoryId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("int");

                    b.Property<bool>("AiReview")
                        .HasColumnType("bit");

                    b.Property<bool>("Architecture")
                        .HasColumnType("bit");

                    b.Property<bool>("Debug")
                        .HasColumnType("bit");

                    b.Property<string>("DebugNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Quality")
                        .HasColumnType("bit");

                    b.Property<bool>("Ready")
                        .HasColumnType("bit");

                    b.Property<bool>("Understand")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Organization", "Project", "RepositoryId", "PullRequestId");

                    b.ToTable("pr_checklists", (string)null);
                });

            modelBuilder.Entity("PRCockpit.Infrastructure.Persistence.Entities.PrFileExplanationRow", b =>
                {
                    b.Property<string>("Organization")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Project")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RepositoryId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("BlobId")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("HeadCommitSha")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Organization", "Project", "RepositoryId", "PullRequestId", "FilePath");

                    b.ToTable("pr_file_explanations", (string)null);
                });

            modelBuilder.Entity("PRCockpit.Infrastructure.Persistence.Entities.PrFileReviewRow", b =>
                {
                    b.Property<string>("Organization")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Project")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RepositoryId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("ChangedFilesCount")
                        .HasColumnType("int");

                    b.Property<string>("ReviewedBlobId")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ReviewedHeadSha")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Organization", "Project", "RepositoryId", "PullRequestId", "FilePath");

                    b.ToTable("pr_file_reviews", (string)null);
                });

            modelBuilder.Entity("PRCockpit.Infrastructure.Persistence.Entities.PrReadingPathRow", b =>
                {
                    b.Property<string>("Organization")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Project")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RepositoryId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("int");

                    b.Property<string>("PathsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Organization", "Project", "RepositoryId", "PullRequestId");

                    b.ToTable("pr_reading_paths", (string)null);
                });

            modelBuilder.Entity("PRCockpit.Infrastructure.Persistence.Entities.PrSummaryRow", b =>
                {
                    b.Property<string>("Organization")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Project")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RepositoryId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("int");

                    b.Property<string>("HeadCommitSha")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Organization", "Project", "RepositoryId", "PullRequestId");

                    b.ToTable("pr_summaries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
