<script setup lang="ts">
// The middle of an open pull request: the open file with its toolbar, comments and AI
// explanation, or the PR description when no file is open. In the walkthrough it also
// carries the step bar and the step actions.
import { computed } from 'vue'
import { useCockpit } from '@/cockpit'
import { commentPreview, renderDescription } from '@/lib/description'
import { fileDirectory, fileName } from '@/lib/format'
import CommentDraft from '@/features/comments/CommentDraft.vue'
import CommentThread from '@/features/comments/CommentThread.vue'
import CommentZoneCard from '@/features/comments/CommentZoneCard.vue'
import CommentsView from '@/features/comments/CommentsView.vue'
import { isResolved } from '@/features/comments/useComments'
import FileChat from '@/features/file-ai/FileChat.vue'

const { details, diff, fileList, summary, review, walk, comments, fileAi, openFile, stepFile, showBriefing, toggleReviewed } = useCockpit()
const {
  selectedFilePath, fileDiff, diffLoading, diffError, diffSinceIteration, lastFilePath, monacoComponent,
  sideBySide, usageSource, filePosition, goToDiff,
} = diff
const { hasPreviousFile, hasNextFile } = fileList
const { roleByPath } = summary
const { walkPosition, isReviewed } = review
const { view, walkPaths, walkFilePath, walkAdvance, walkBack, leaveWalkthrough } = walk
const {
  commentsOpen, draft, commentError, inlineThreadId, inlineThread, inlineThreadIndex, lineDraft, threadsInFile,
  commentLinesForFile, resolvedLinesForFile, zoneTargets, zoneCards, zoneLines, showComments, useZones,
  openLineComments, openThreadInFile, stepThreadInFile, closeInlineComments, commentOnCursorLine,
} = comments
const {
  explanation, explanationLoading, explanationError, explanationOpen, questionOpen, questionTurns,
  resetExplanation, explainFile, openQuestions,
} = fileAi

const lastFileName = computed(() => lastFilePath.value ? fileName(lastFilePath.value) : '')
const descriptionHtml = computed(() => details.value?.description
  ? renderDescription(details.value.description, details.value.workItems)
  : '')
// j/k/m deliberately do not move focus, so a screen reader needs this spoken instead.
const readingStatus = computed(() => filePosition.value && details.value
  ? `Plik ${filePosition.value} z ${details.value.changedFilesCount} · ${selectedFilePath.value}`
  : '')
</script>

<template>
  <div v-if="details" :ref="diff.diffPanel" class="diff-panel">
    <!-- US-P4. Position in the path, not in the Azure DevOps file list: the
         walkthrough counts what it walks. -->
    <div v-if="view === 'walk'" class="walk-bar">
      <span class="walk-progress">Krok {{ walkPosition + 1 }} z {{ walkPaths.length }}</span>
      <span class="walk-bar-file" :title="walkFilePath">{{ fileName(walkFilePath) }}<small>{{ fileDirectory(walkFilePath) }}</small></span>
      <span v-if="roleByPath.get(walkFilePath)" class="walk-bar-role">{{ roleByPath.get(walkFilePath) }}</span>
    </div>
    <!-- Nothing is generated by walking in here: an explanation costs a model run,
         so it happens when asked for and not a file sooner. Asking lives in the
         toolbar below and on `e`, so this section exists only once there is
         something to read — an empty panel holding one button was two rows of
         chrome for an action that was already on screen. -->
    <section v-if="view === 'walk' && (explanation || explanationError)" class="walk-explanation"
      aria-label="Wyjaśnienie pliku">
      <p v-if="explanation" class="walk-explanation-text">{{ explanation.sentences.join(' ') }}</p>
      <p v-else class="notice error" role="alert">
        {{ explanationError }}
        <button class="checklist-retry" type="button" :disabled="explanationLoading" @click="explainFile">Ponów</button>
      </p>
    </section>
    <CommentsView v-if="commentsOpen" />
    <template v-else-if="selectedFilePath">
      <div class="diff-toolbar">
        <div class="diff-toolbar-title" :title="selectedFilePath"><h4>{{ fileName(selectedFilePath) }}</h4><span>{{ fileDirectory(selectedFilePath) }}</span></div>
        <span v-if="filePosition" class="diff-position">Plik {{ filePosition }} z {{ details.changedFilesCount }}</span>
        <div class="diff-actions">
          <span class="diff-actions-label">Plik</span>
          <button type="button" title="Poprzedni plik (k)" aria-label="Poprzedni plik"
            :disabled="!hasPreviousFile" @click="stepFile(-1)">‹</button>
          <button type="button" title="Następny plik (j)" aria-label="Następny plik"
            :disabled="!hasNextFile" @click="stepFile(1)">›</button>
          <span class="diff-actions-label">Zmiana</span>
          <button type="button" title="Poprzednia zmiana w pliku (,)" aria-label="Poprzednia zmiana w pliku" @click="goToDiff('previous')">‹</button>
          <button type="button" title="Następna zmiana w pliku (.)" aria-label="Następna zmiana w pliku" @click="goToDiff('next')">›</button>
          <button type="button" class="diff-layout-toggle" :aria-pressed="sideBySide" @click="sideBySide = !sideBySide">{{ sideBySide ? 'Obok siebie' : 'W linii' }}</button>
          <button type="button" title="Opis PR (o)" @click="showBriefing">Opis PR</button>
          <!-- Renderowany zawsze, choćby wyłączony: pod v-if kolejne przyciski
               przeskakiwały w poziomie na każdym pliku z komentarzem. -->
          <button type="button" class="comments-toggle" :disabled="!threadsInFile.length"
            :aria-pressed="showComments" :title="showComments ? 'Ukryj komentarze w kodzie' : 'Pokaż komentarze w kodzie'"
            @click="showComments = !showComments">{{ showComments && threadsInFile.length ? 'Ukryj komentarze' : `Pokaż komentarze (${threadsInFile.length})` }}</button>
          <button type="button" class="comment-line-button" title="Skomentuj linię pod kursorem"
            :disabled="!fileDiff || fileDiff.kind !== 'text'" @click="commentOnCursorLine">Skomentuj linię</button>
          <button type="button" class="explain-button" title="Wyjaśnij ten plik (e)"
            :disabled="explanationLoading" @click="explainFile">{{ explanationLoading ? 'Wyjaśniam…' : 'Wyjaśnij ten plik' }}</button>
          <button type="button" class="ask-button" title="Zapytaj o ten plik (a)"
            :aria-pressed="questionOpen" :disabled="!fileDiff" @click="openQuestions()">Zapytaj o plik<span
              v-if="questionTurns.length"> ({{ questionTurns.length }})</span></button>
        </div>
        <label class="review-check"><input type="checkbox" :checked="isReviewed(selectedFilePath)" :disabled="!fileDiff && !isReviewed(selectedFilePath)" @change="toggleReviewed"> Obejrzałem</label>
      </div>
      <p v-if="diffSinceIteration" class="notice diff-since" role="status">
        Pokazuję wyłącznie zmiany od iteracji {{ diffSinceIteration }} — czyli to, co dopisano później.
        <button type="button" class="checklist-retry" @click="openFile(selectedFilePath, null)">Pokaż cały diff</button>
      </p>
      <p class="reading-status" aria-live="polite">{{ readingStatus }}</p>
      <!-- Every thread in this file, so comments are visible on arrival instead of
           having to be found. A chip opens the conversation below it. -->
      <div v-if="threadsInFile.length" class="file-threads">
        <span class="file-threads-label">Komentarze w pliku:</span>
        <button v-for="thread in threadsInFile" :key="thread.id" type="button"
          class="file-thread-chip" :class="{ 'file-thread-chip--resolved': isResolved(thread) }"
          :aria-pressed="inlineThreadId === thread.id"
          :title="thread.comments[0]?.content ? commentPreview(thread.comments[0].content) : ''"
          @click="openThreadInFile(thread)">
          {{ isResolved(thread) ? '✓' : '💬' }} {{ thread.rightLine ? `linia ${thread.rightLine}` : 'plik' }}
        </button>
      </div>
      <!-- The conversation for the clicked line, docked above the diff so the code
           it is about stays on screen. Only where there is no editor to hold zones. -->
      <div v-if="!useZones && (inlineThread || lineDraft !== null)" class="inline-comments">
        <div class="inline-comments-head">
          <strong>{{ inlineThread ? `Komentarz w linii ${inlineThread.rightLine ?? '—'}` : `Nowy komentarz do linii ${lineDraft}` }}</strong>
          <template v-if="inlineThread && threadsInFile.length > 1">
            <span class="inline-position">{{ inlineThreadIndex + 1 }} z {{ threadsInFile.length }}</span>
            <button type="button" aria-label="Poprzedni komentarz w pliku" @click="stepThreadInFile(-1)">‹</button>
            <button type="button" aria-label="Następny komentarz w pliku" @click="stepThreadInFile(1)">›</button>
          </template>
          <button type="button" class="inline-close" @click="closeInlineComments">Zamknij</button>
        </div>
        <p v-if="commentError" class="notice error" role="alert">{{ commentError }}</p>
        <CommentThread v-if="inlineThread" :thread="inlineThread" />
        <CommentDraft v-else-if="draft" label="Treść komentarza do linii" @cancel="closeInlineComments" />
      </div>
      <!-- Not in the walkthrough: there the explanation already has its own panel
           above the diff, and the same few sentences twice on one screen is noise. -->
      <p v-if="explanationError && view !== 'walk'" class="notice error file-explanation-error" role="alert">{{ explanationError }}</p>
      <!-- Foldable like a comment: it is a few sentences you read once, and it was
           holding the top of the panel for the rest of the file. -->
      <details v-if="explanation && view !== 'walk'" class="file-explanation" :open="explanationOpen" aria-label="Wyjaśnienie pliku"
        @toggle="explanationOpen = ($event.target as HTMLDetailsElement).open">
        <summary class="file-explanation-summary">Wyjaśnienie AI<span v-if="!explanationOpen"> · {{ explanation.sentences[0] }}</span></summary>
        <p v-for="(sentence, index) in explanation.sentences" :key="index">{{ sentence }}</p>
        <p class="file-explanation-note muted">Dla tej wersji pliku. Zapisane lokalnie.
          <button type="button" class="explanation-dismiss" @click="resetExplanation">Ukryj</button>
        </p>
      </details>
      <!-- Shown in the walkthrough too — that is where you read code you did not
           write, and the explanation's second panel has no equivalent here. -->
      <FileChat v-if="questionOpen" />
      <p v-if="diffLoading" class="diff-message muted" role="status">Pobieranie diffu…</p>
      <p v-else-if="diffError" class="diff-message notice error" role="alert">{{ diffError }}</p>
      <p v-else-if="fileDiff?.kind === 'binary'" class="diff-message muted">Plik binarny — diff tekstowy jest niedostępny.</p>
      <p v-else-if="fileDiff?.kind === 'tooLarge'" class="diff-message muted">Plik jest zbyt duży, aby pokazać diff (limit 256 KB na wersję lub 4000 linii łącznie).</p>
      <component :is="monacoComponent" v-else-if="fileDiff?.kind === 'text' && monacoComponent" :ref="diff.diffView" :path="fileDiff.path"
        :original-path="fileDiff.originalPath" :original-text="fileDiff.originalText" :modified-text="fileDiff.modifiedText"
        :side-by-side="sideBySide" :comment-lines="commentLinesForFile" :resolved-lines="resolvedLinesForFile"
        :zone-lines="zoneLines" :usages="usageSource" @open-line="openLineComments" @zones="zoneTargets = $event" @ask="openQuestions($event)" />
      <Teleport v-for="zone in zoneCards" :key="zone.line" :to="zone.el">
        <CommentZoneCard :line="zone.line" :thread="zone.thread" />
      </Teleport>
    </template>
    <div v-else class="pr-briefing">
      <button v-if="lastFilePath" class="briefing-back" type="button" title="Wróć do pliku (o)"
        @click="openFile(lastFilePath)">← Wróć do {{ lastFileName }}</button>
      <h3>O co chodzi w tym PR</h3>
      <p v-if="!details.description" class="muted">Brak opisu.</p>
      <div v-else class="description markdown-body" v-html="descriptionHtml" />
      <p class="diff-placeholder">Wybierz plik z listy, aby zobaczyć jego diff.</p>
    </div>

    <!-- US-P4 zone 4: reachable without scrolling the diff, so the end of a file is
         always one click away. -->
    <div v-if="view === 'walk'" class="walk-actions walk-actions--sticky">
      <button type="button" class="walk-primary" @click="walkAdvance(true)">
        {{ walkPosition + 1 >= walkPaths.length ? 'Przeczytane · zakończ przejście' : 'Przeczytane, dalej (m)' }}
      </button>
      <button type="button" title="Dalej bez oznaczania jako przeczytane" @click="walkAdvance(false)">Pomiń</button>
      <button type="button" title="Poprzedni krok (k)" :disabled="walkPosition === 0" @click="walkBack">← Wstecz</button>
      <button type="button" title="Wyjdź z przejścia (Esc)" @click="leaveWalkthrough">Wyjdź z przejścia</button>
    </div>
  </div>
</template>

<style scoped>
.diff-panel { min-width: 0; min-height: 0; border: 1px solid var(--line-strong); border-radius: var(--radius); overflow: hidden; }
.diff-panel { display: flex; flex-direction: column; scroll-margin-top: 16px; background: var(--surface-muted); }
.diff-toolbar { display: flex; align-items: center; justify-content: space-between; gap: 10px; flex: none; padding: 10px 14px; border-bottom: 1px solid var(--line-strong); background: var(--surface); }
.diff-toolbar-title { min-width: 0; }
.diff-toolbar-title h4, .diff-toolbar-title span { display: block; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.diff-toolbar-title h4 { margin: 0; font-size: 14px; }
.diff-toolbar-title span { margin-top: 3px; color: var(--text-muted); font-family: Consolas, 'Courier New', monospace; font-size: 11px; }
.review-check { display: flex; align-items: center; gap: 7px; flex: none; padding: 6px 12px; border: 1px solid var(--border-button); border-radius: 6px; background: var(--surface); color: var(--text-strong); font-size: 13px; font-weight: 700; white-space: nowrap; cursor: pointer; }
.review-check:hover:has(input:not(:disabled)) { border-color: var(--accent); }
.review-check:has(input:checked) { border-color: var(--ok-line); background: var(--ok-bg); color: var(--ok); }
.review-check:has(input:disabled) { opacity: .55; cursor: not-allowed; }
.review-check input { width: 16px; height: 16px; margin: 0; accent-color: var(--accent); }
.diff-placeholder { margin: auto; padding: 20px; color: var(--text-muted); text-align: center; }
.diff-message { margin: 16px; }
.pr-briefing { min-height: 0; overflow-y: auto; padding: 24px 28px; }
.pr-briefing h3 { font-size: 16px; }
.pr-briefing .description { max-width: 80ch; }
.pr-briefing .diff-placeholder { margin: 28px 0 0; padding: 0; text-align: left; font-size: 13px; }
.diff-position { flex: none; color: var(--text-muted); font-size: 12px; font-weight: 700; white-space: nowrap; }
.diff-actions { display: flex; flex: none; gap: 4px; align-items: center; }
.diff-actions-label { color: var(--text-muted); font-size: 11px; font-weight: 700; }
.diff-actions-label + button { margin-left: 2px; }
.diff-actions-label:not(:first-child) { margin-left: 8px; }
.diff-actions button { min-width: 30px; min-height: 28px; padding: 2px 8px; border: 1px solid var(--line-strong); border-radius: 5px; background: var(--surface); color: var(--text-strong); font-size: 12px; }
.diff-layout-toggle { font-weight: 700; }
.diff-layout-toggle[aria-pressed="true"] { border-color: var(--accent); background: var(--accent-soft); color: var(--accent); }
/* Announced to screen readers only: the keyboard shortcuts move files without moving focus. */
.reading-status { position: absolute; width: 1px; height: 1px; margin: -1px; padding: 0; overflow: hidden; clip-path: inset(50%); white-space: nowrap; }
.file-explanation { margin: 0 12px 8px; padding: 8px 10px; border-left: 3px solid var(--accent); background: var(--surface-muted); border-radius: 0 6px 6px 0; }
.file-explanation p { margin: 0 0 4px; font-size: 13px; }
.file-explanation-summary { font-size: 13px; font-weight: 600; cursor: pointer; }
.file-explanation-summary span { font-weight: 400; color: var(--text-muted); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; display: inline-block; max-width: 60ch; vertical-align: bottom; }
.file-explanation[open] .file-explanation-summary { margin-bottom: 6px; }
.file-explanation-note { font-size: 12px; margin-bottom: 0 !important; display: flex; align-items: center; gap: 8px; }
.file-explanation-error { margin: 0 12px 8px; }
.diff-since { margin: 0 12px 8px; display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
/* A review comment can be two screens of Markdown. It is never truncated — the block
   scrolls inside itself and `resize` lets you give it as much of the panel as you want,
   which is the browser's own handle rather than a drag implementation of ours. */
.inline-comments { flex: 0 1 auto; margin: 0 12px 8px; padding: 8px 10px; height: 34vh; min-height: 90px; max-height: 80vh; overflow-y: auto; resize: vertical; border: 1px solid var(--line); border-left: 3px solid var(--accent); border-radius: 0 6px 6px 0; background: var(--surface-muted); }
.inline-comments-head { position: sticky; top: -8px; background: var(--surface-muted); padding: 2px 0; z-index: 1; }
.inline-position { font-size: 12px; color: var(--text-muted); }
.inline-comments-head { display: flex; align-items: baseline; gap: 8px; font-size: 13px; }
.file-threads { display: flex; flex-wrap: wrap; align-items: center; gap: 6px; margin: 0 12px 8px; }
.file-threads-label { font-size: 12px; color: var(--text-muted); }
.file-thread-chip { font-size: 12px; padding: 2px 8px; border-radius: 999px; }
.file-thread-chip--resolved { opacity: .6; }
.file-thread-chip[aria-pressed="true"] { border-color: var(--accent); color: var(--accent); }
.briefing-back { margin-bottom: 16px; padding: 7px 12px; border: 1px solid var(--border-button); border-radius: 6px; background: var(--surface); color: var(--text-strong); font-size: 13px; font-weight: 700; }
.walk-bar-file small { margin-left: 6px; color: var(--text-muted); font-weight: 400; font-size: 11px; }
/* Zone 4 of US-P4: the diff scrolls, this does not. */
.walk-actions--sticky { position: sticky; bottom: 0; margin: 0; padding: 8px 12px; border-top: 1px solid var(--line); background: var(--surface); }
.walk-bar { display: flex; flex-wrap: wrap; align-items: baseline; gap: 10px; padding: 8px 12px; border-bottom: 1px solid var(--line); background: var(--surface-muted); }
.walk-progress { flex: none; color: var(--accent); font-weight: 800; font-size: 13px; }
.walk-bar-file { flex: 1 1 200px; min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-weight: 700; }
.walk-bar-role { flex: 0 1 auto; min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: var(--text-muted); font-size: 12px; }
.walk-explanation { margin: 8px 12px 0; padding: 6px 10px; border-left: 3px solid var(--accent); background: var(--surface-muted); border-radius: 0 6px 6px 0; }
.walk-explanation-text { margin: 4px 0 0; font-size: 13px; }

@media (max-width: 900px) {
  .diff-panel { height: min(76vh, 720px); min-height: 340px; }
}

@media (max-width: 720px) {
  .diff-toolbar { align-items: flex-start; flex-direction: column; }
}
</style>
